### ISSUE TITLE
Interested in the project

### ISSUE THREAD

**Issue by alexweber** [ormjs/orm.js-legacy#6]
Hi, I found Persistence.js while looking for a JS-ORM to use with Ionic Framework + Cordova SQLite and so far it's been working pretty well...

I'd noticed that the main repo is abandoned and stumbled upon this fork and noticed that it's been pretty much the two of you maintaining this and rewriting the new version...

I'm not a javascript guru by any means but I might be able to help with some of the more menial tasks... I don't have a lot of time but I have a great interest in this project... wondering if there's a Gitter chat or mailing list or somewhere I could start getting involved...

Thanks! :)

**Comment by TheCodeDestroyer** [comment]
Sure! Any help would be appreciated!
Since both Chris and I don't have much spare time as well.
I create a contributors team and invited you in it.
And we have a gitter chat as well, you cna find it [here](https://gitter.im/ormjs)

**Comment by alexweber** [comment]
Thanks!
